---
# tasks file for mongodb
- name: Add mongodb repository
  apt_repository: 
    repo: 'deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.2 main'
    state: present
  when: ansible_architecture == "x86_64"

- name: Add repository key
  apt_key: 
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
  when: ansible_architecture == "x86_64"

- name: Install MongoDB
  apt: 
    name: mongodb-org
    state: present
    update_cache: yes
  when: ansible_architecture == "x86_64"

- name: Install MongoDB (32bit, for raspberry pi's)
  apt: 
    name: mongodb-server
    state: present
    force: yes
  when: ansible_architecture == "armv7l"


