---
# tasks file for sys-config

#- name: Add a damn working repository 1
#  apt_repository: repo='deb http://ftp.se.debian.org/debian/ jessie main' state=present

#- name: Add a damn working repository 2
 # apt_repository: repo='deb-src http://ftp.se.debian.org/debian/ jessie main' state=present

- name: Update systems
  apt: update_cache=yes

# Add user groups
- name: Make sure user groups are present
  group: name={{ item.value.group }} state=present
  with_dict: "{{ users }}"

# Add users
- name: Make new users if not already present
  user: name={{ item.value.name }} state=present group={{ item.value.group }} createhome=yes
  with_dict: "{{ users }}"

# do a line edit for passwordless sudo
- name: Allow 'administrator' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%administrator'
    line: '%administrator ALL=(ALL) NOPASSWD: ALL'

# Add authorized keys for administrator
- name: Set up authorized keys for the "ansible_user" user
  authorized_key: user=administrator key="{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

