- name: Update Package cache
  apt: update_cache=yes cache_valid_time=360

- name: Install NPM
  apt: name=npm state=present

- name: Install N
  npm: name=n state=present global=yes 

- name: Install Nodejs
  shell: n stable

- name: Install Nodemon
  npm: name=nodemon state=present global=yes

- name: Install PM2
  npm: name=pm2 state=present global=yes

- name: Install forever (to run Node.js app).
  npm: name=forever global=yes state=present

- name: Install git
  apt: name=git state=present

- name: Install tmux
  apt: name=tmux state=present


